kind = "web"
previewPath = "/"
title = "Navii"
version = "1.0.0"
id = "artifacts/navii"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20233

[services.development]
run = "pnpm --filter @workspace/navii run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/navii", "run", "build" ]
publicDir = "artifacts/navii/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20233"
BASE_PATH = "/"
